[package]
name = "push_the_elephant"
version = "0.0.1"
authors = ["fcracker79 <fcracker79@gmail.com>"]
edition = "2018"

[dependencies]
postgres = "0.15"
kafka = "0.7"
derive_builder = "0.7.2"
fallible-iterator = "0.1.3"
serde_json = "1.0"
log = "0.4.7"
