language: rust
rust:
  - 1.36.0

services:
  - postgresql
  - docker

cache: cargo
before_cache:
  - rm -rfv target/debug/incremental/push_the_elephant-*
  - rm -rfv target/debug/.fingerprint/push_the_elephant-*
  - rm -rfv target/debug/build/push_the_elephant-*
  - rm -rfv target/debug/deps/libpush_the_elephant-*
  - rm -rfv target/debug/deps/push_the_elephant-*
  - rm -rfv target/debug/push_the_elephant,libpush_the_elephant}.d
  - cargo clean -p push_the_elephant

before_script:
  - docker swarm init
  - docker network create -d overlay confluent_network
  - docker stack deploy -c travis/kafka.yml confluent
  - psql -c "create database push_the_elephant;" -U postgres
  - psql -c "create user push_the_elephant with encrypted password 'push_the_elephant';" -U postgres
  - psql -c "grant all privileges on database push_the_elephant to push_the_elephant;" -U postgres
  - psql -f sql/init.sql -U postgres push_the_elephant;
