[package]
name = "pte"
version = "0.0.1"
authors = ["fcracker79 <fcracker79@gmail.com>"]
edition = "2018"

[dependencies]
push_the_elephant = { path = "../push_the_elephant" }
clap = "2.33.0"
log4rs = "0.8.3"
log = "0.4.7"
